title: "My Lazzy Blog"
description: "My Personal Experimentations"
author:
  name: ""
  email: "lazyblogging@home.au"
  url: "https://miomirparipovic.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "LazzyBlogger"
year : "2023"
